-- how to create Database
CREATE DATABASE STUDENT_DETAILS;

show databases;

drop database STUDENT_DETAILS;

USE STUDENT_DETAILS;

CREATE TABLE STUDENT(
   ID INT UNSIGNED NOT NULL auto_increment PRIMARY KEY,
   FIRST_NAME VARCHAR(20) NOT NULL,
   LAST_NAME VARCHAR(20) NOT NULL,
   CITY CHAR(20) NOT NULL,
   AGE INT UNSIGNED NOT NULL,
   DATE_OF_JOINING DATE NOT NULL,
   RESULT ENUM('PASS','FAIL','AWAITED') NOT NULL DEFAULT 'AWAITED');
   
CREATE TABLE DEGREE(
   DEGREE_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   COURSE_NAME VARCHAR(50) NOT NULL,
   LENGTH_OF_COURSE INT UNSIGNED NOT NULL CHECK(LENGTH_OF_COURSE>=3),
   FEES DECIMAL(8,2)
   )AUTO_INCREMENT=5000;
   
   SHOW TABLES;
   
   DESCRIBE DEGREE;
   
   
   CREATE TABLE ENROLLMENT(
   SID INT UNSIGNED NOT NULL,
   MARKS INT UNSIGNED NOT NULL CHECK(MARKS<=100),
   DID INT UNSIGNED NOT NULL,
   FOREIGN KEY(SID) REFERENCES STUDENT_DATA(ID)
   );
   

   DESCRIBE ENROLLMENT;
   