
-- CHANGE AND MODIFIEY THE TABLE COLUMN 

   ALTER TABLE STUDENT CHANGE DATE_OF_JOINING ADMISSION_DATE DATE NOT NULL;
   
   ALTER TABLE STUDENT MODIFY CITY VARCHAR(20) NOT NULL;
   
   ALTER TABLE DEGREE CHANGE COURSE_NAME DEGREE_NAME VARCHAR(50)NOT NULL;
   
   
   ALTER TABLE DEGREE RENAME DEGREE_DETAILS;
   
   ALTER TABLE STUDENT RENAME STUDENT_DATA;
   
   ALTER TABLE DEGREE_DETAILS ADD COLUMN MAX_MARKS INT UNSIGNED NOT NULL;
   
   ALTER TABLE DEGREE_DETAILS DROP COLUMN MAX_MARKS;
   
   ALTER TABLE DEGREE_DETAILS ADD COLUMN MIN_MARKS INT UNSIGNED NOT NULL;
   
   
   ALTER TABLE ENROLLMENT ADD FOREIGN KEY(DID) REFERENCES DEGREE_DETAILS(DEGREE_ID);
   
   ALTER TABLE ENROLLMENT DROP CONSTRAINT ENROLLMENT_IBFK_2;
   ALTER TABLE ENROLLMENT DROP KEY DID;
   ALTER TABLE ENROLLMENT DROP COLUMN DID;
   
   
   ALTER TABLE ENROLLMENT ADD COLUMN DEG_ID INT UNSIGNED NOT NULL;
   
   ALTER TABLE ENROLLMENT ADD FOREIGN KEY(Deg_ID) references Degree_Details(Degree_Id);

   